### PR TITLE
Fixed env tests checking for --all-dirs flag

### LINKED ISSUE #563: tests should not fail when: $TMPDIR is set
The new test `TestAllDir` fails when the env variable `TMPDIR` is set to point to within the home directory.

The stripped table output contains: `$NKEYS_PATH No ~/tmp/nsc_test1638242485`  
The test complains: `does not contain "$NKEYS_PATH Yes /home/myusercode/tmp/nsc_test1638242485"`

This has two different expectations of normalization.

### PR DESCRIPTION
**Pull request by aricart**
[TEST] changed tests to deduce the effect of the flag without relying on the env.

[FIX] deprecated NKEYS_PATH and NSC_HOME - installations should use XDG_DATA_HOME and XDG_CONFIG_HOME instead. Added these variables to the `nsc env` report

Fixes #563

### CODE REVIEW

File: home/home.go [hunk 1]
```diff
@@ -24,9 +24,11 @@ import (
 
 const StoresSubDirName = "stores"
 const KeysSubDirName = "keys"
+const XdgConfigHome = "XDG_CONFIG_HOME"
+const XdgDataHome = "XDG_DATA_HOME"
 
 var home, _ = homedir.Dir()
-var config = envOrValue("XDG_CONFIG_HOME", filepath.Join(home, ".config"))
+var config = envOrValue(XdgConfigHome, filepath.Join(home, ".config"))
 var data = envOrValue("XDG_DATA_HOME", filepath.Join(home, ".local", "share"))
```
Comment (Jarema) [inline home/home.go:32]: If we added const, let's use it here.

**Review by Jarema — CHANGES_REQUESTED** [review]
one small nit.

File: home/home.go (hunk 1 above)
Comment (aricart) [reply home/home.go:32]: good catch
