### PR TITLE
FIX #265 - adding a user in interactive mode could add bogus IssuerAccount

### LINKED ISSUE #265: nsc in interactive mode adds unexpected field issuer_account wrongly pointing to nsc default account
Given the following sequence of commands: I create an operator, two accounts, then a users in each account (using interactive mode).
The generated jwt for the user in the account that's not the default account contains an extra field issuer_account pointing to the default account.

decodejwt is a shell function I wrote for myself, does what you'd expect.

```
19:54:34  ~  nsc add operator OP
[ OK ] generated and stored operator key "OA4LSFBW2RYBDL4HCSXJSS4YGFVE43OSQY4UY6KJ7QLE73PJ6SNBORBV"
[ OK ] added operator "OP"
 19:54:41  ~  nsc add account SYS
[ OK ] generated and stored account key "AA6PHN3KJT3AAYWL225BFOVIDGUEJL3VAIBERQ2DLUX4Z7YCKY5Y4OGJ"
[ OK ] added account "SYS"
 19:54:44  ~  nsc add account USERS
[ OK ] generated and stored account key "AAZJZFMKOV2HRMXS4675AFTFBEUIJ5FH7YXQUNY42766NP47F6666W5W"
[ OK ] added account "USERS"
 19:54:50  ~  nsc add user -i
? select account SYS
? user name S1
? generate an user nkey Yes
? valid 0
? valid until (0 is always) 0
[ OK ] generated and stored user key "UAVZJE7YE74LLGRXEXEUALQ2UKF3QQ75W7AK7JCOAZWDEVZMIDXAD57O"
[ OK ] generated user creds file `~/.nkeys/creds/OP/SYS/S1.creds`
[ OK ] added user "S1" to account "SYS"
 19:55:02  ~  nsc add user -i
? select account USERS
? user name U1
? generate an user nkey Yes
? valid 0
? valid until (0 is always) 0
[ OK ] generated and stored user key "UCXMY5GM44F42SV25U5NBZXSC23W3YSDBR6ZY6UFUIPGCYJ25WURN3XF"
[ OK ] generated user creds file `~/.nkeys/creds/OP/USERS/U1.creds`
[ OK ] added user "U1" to account "USERS"
 19:55:24  ~  cd .nsc/nats/OP
 19:55:26  ~/.nsc/nats/OP  ls
OP.jwt   accounts
 19:55:28  ~/.nsc/nats/OP  cd accounts
 19:55:38  ~/.nsc/nats/OP/accounts  decodejwt SYS/SYS.jwt
{"typ":"jwt","alg":"ed25519"}

{"jti":"MM2FKSEGK442KI4E6V3L2HPBK4QZJ3XL3TOMN3CQHZU54VBB7PDQ","iat":1585353281,"iss":"OA4LSFBW2RYBDL4HCSXJSS4YGFVE43OSQY4UY6KJ7QLE73PJ6SNBORBV","name":"SYS","sub":"AA6PHN3KJT3AAYWL225BFOVIDGUEJL3VAIBERQ2DLUX4Z7YCKY5Y4OGJ","type":"account","nats":{"limits":{"subs":-1,"conn":-1,"leaf":-1,"imports":-1,"exports":-1,"data":-1,"payload":-1,"wildcards":true}}}%                                                                                                                                  19:55:47  ~/.nsc/nats/OP/accounts  decodejwt USERS/USERS.jwt
{"typ":"jwt","alg":"ed25519"}

{"jti":"XHSZROPHQKEINY3XJOP6RH77ICDEFBM4EADRWK64D3AQMJQB4KPA","iat":1585353284,"iss":"OA4LSFBW2RYBDL4HCSXJSS4YGFVE43OSQY4UY6KJ7QLE73PJ6SNBORBV","name":"USERS","sub":"AAZJZFMKOV2HRMXS4675AFTFBEUIJ5FH7YXQUNY42766NP47F6666W5W","type":"account","nats":{"limits":{"subs":-1,"conn":-1,"leaf":-1,"imports":-1,"exports":-1,"data":-1,"payload":-1,"wildcards":true}}}%                                                                                                                           19:55:58  ~/.nsc/nats/OP/accounts  decodejwt SYS/users/S1.jwt
{"typ":"jwt","alg":"ed25519"}

{"jti":"N7EFRX2FTV5YFQF7HFE3QHCEAP4UE4Q4NZG2ILP723AESQZYMIXA","iat":1585353300,"iss":"AA6PHN3KJT3AAYWL225BFOVIDGUEJL3VAIBERQ2DLUX4Z7YCKY5Y4OGJ","name":"S1","sub":"UAVZJE7YE74LLGRXEXEUALQ2UKF3QQ75W7AK7JCOAZWDEVZMIDXAD57O","type":"user","nats":{"pub":{},"sub":{}},"issuer_account":"AAZJZFMKOV2HRMXS4675AFTFBEUIJ5FH7YXQUNY42766NP47F6666W5W"}%                                                                                                                 19:56:19  ~/.nsc/nats/OP/accounts  decodejwt USERS/users/U1.jwt
{"typ":"jwt","alg":"ed25519"}

{"jti":"B35Z364J7QE55E3D4RFNDKK7DT2KC4CCSYHFYJS2RYGHRYKWN6MA","iat":1585353315,"iss":"AAZJZFMKOV2HRMXS4675AFTFBEUIJ5FH7YXQUNY42766NP47F6666W5W","name":"U1","sub":"UCXMY5GM44F42SV25U5NBZXSC23W3YSDBR6ZY6UFUIPGCYJ25WURN3XF","type":"user","nats":{"pub":{},"sub":{}}}%

Why does S1 from account SYS have an extra field, compared to S1 from account USERS.
Why is this "issuer_account" pointing to USERS? (see below)
For completeness I list all keys, so I can see the structure, it appears as I would have thought it'd happen?

19:56:44  ~/.nsc/nats/OP/accounts  nsc list keys --all | grep AAZJZFMKOV2HRMXS4675AFTFBEUIJ5FH7YXQUNY42766NP47F6666W5W
│  USERS │ AAZJZFMKOV2HRMXS4675AFTFBEUIJ5FH7YXQUNY42766NP47F6666W5W │             │ *      │
19:56:52  ~/.nsc/nats/OP/accounts  nsc list keys --all
╭──────────────────────────────────────────────────────────────────────────────────────────╮
│                                           Keys                                           │
├────────┬──────────────────────────────────────────────────────────┬─────────────┬────────┤
│ Entity │ Key                                                      │ Signing Key │ Stored │
├────────┼──────────────────────────────────────────────────────────┼─────────────┼────────┤
│ OP     │ OA4LSFBW2RYBDL4HCSXJSS4YGFVE43OSQY4UY6KJ7QLE73PJ6SNBORBV │             │ *      │
│  SYS   │ AA6PHN3KJT3AAYWL225BFOVIDGUEJL3VAIBERQ2DLUX4Z7YCKY5Y4OGJ │             │ *      │
│   S1   │ UAVZJE7YE74LLGRXEXEUALQ2UKF3QQ75W7AK7JCOAZWDEVZMIDXAD57O │             │ *      │
│  USERS │ AAZJZFMKOV2HRMXS4675AFTFBEUIJ5FH7YXQUNY42766NP47F6666W5W │             │ *      │
│   U1   │ UCXMY5GM44F42SV25U5NBZXSC23W3YSDBR6ZY6UFUIPGCYJ25WURN3XF │             │ *      │
╰────────┴──────────────────────────────────────────────────────────┴─────────────┴────────╯

20:15:21  ~/.nsc/nats/OP/accounts  nsc env
╭──────────────────────────────────────────╮
│             NSC Environment              │
├──────────────────┬─────┬─────────────────┤
│ Setting          │ Set │ Effective Value │
├──────────────────┼─────┼─────────────────┤
│ $NKEYS_PATH      │ No  │ ~/.nkeys        │
│ $NSC_HOME        │ No  │ ~/.nsc          │
│ Config           │     │ ~/.nsc/nsc.json │
├──────────────────┼─────┼─────────────────┤
│ From CWD         │     │ Yes             │
│ Stores Dir       │     │ ~/.nsc/nats     │
│ Default Operator │     │ OP              │
│ Default Account  │     │ USERS           │
╰──────────────────┴─────┴─────────────────╯

 20:15:21  ~/.nsc/nats/OP/accounts 
```

### PR DESCRIPTION
**Pull request by aricart**
The generic entity code interacted with the store directly requesting a context. However add user interactive command changes the context, these changes were not visible by entity. When the entity looked for the public key of the account, it retrieved the one for the one in the context rather than the one for the user selected account.

### CODE REVIEW

File: cmd/adduser.go [hunk 1]
```diff
@@ -108,6 +108,10 @@ type AddUserParams struct {
 	src           []string
 	tags          []string
 	credsFilePath string
+	userName      string
+	create        bool
+	keyPath       string
```
Comment (matthiashanel) [inline cmd/adduser.go]: It seems that create should be called createKey or be deleted as it seems that his is redundant with keyPath being "" or not. 
In the code below what would it mean if creat == false and keyPath == ""?
Add a function (p *AddUserParams) createKey() bool {return p.keyPath == ""}?

File: cmd/adduser.go [hunk 2]
```diff
@@ -140,10 +142,38 @@ func (p *AddUserParams) PreInteractive(ctx ActionCtx) error {
...
+				return err
+			}
+			if t != nkeys.PrefixByteUser {
+				return errors.New("specified key is not a valid for an user")
+			}
+			return nil
+		}))
+		if err != nil {
+			return err
+		}
```
Comment (matthiashanel) [inline cmd/adduser.go]: p.create = false now?

Comment (aricart) [reply cmd/adduser.go]: got rid of create
