### PR TITLE
FIX #103 - ~ in paths are not honored for signing keys.

### LINKED ISSUE #103: key resolution with ~/ paths fails

### PR DESCRIPTION
**Pull request by aricart**

### CODE REVIEW

File: cmd/signerparams_test.go [hunk 1]
```diff
@@ -172,3 +173,30 @@ func Test_SignerParamsPathNotFound(t *testing.T) {
...
 }
+
+func Test_SignerParamsHomePath(t *testing.T) {
+	ts := NewTestStore(t, "O")
+	defer ts.Done(t)
+
+	home, err := homedir.Dir()
+	require.NoError(t, err)
+
+	// yeap not going to remove it
```
Comment (sasbury) [inline cmd/signerparams_test.go]: well this is scary

Comment (aricart) [reply cmd/signerparams_test.go]: just removing the file, not the dir :)
