### PR TITLE
[FIX] added optional timeout for nats-resolver based operations

### LINKED ISSUE #504: add argument to `nsc push` command to set the timeout
Hi team, nsc is very good tool.
But in my environment occurred timed out with `nsc push` frequently. 
Therefore, it would be nice if the timeout could be set from an argument.

### PR DESCRIPTION
**Pull request by aricart**
FIXES #504

### CODE REVIEW

File: cmd/push.go [hunk 1]
```diff
@@ -298,6 +298,12 @@ func (p *PushCmdParams) PostInteractive(_ ActionCtx) error {
 }
 
 func (p *PushCmdParams) Validate(ctx ActionCtx) error {
+	if p.timeout < 1 {
```
Comment (piotrpio) [inline cmd/push.go:301]: Don't you think it would be better to simply return error here to not confuse users? Especially for timeouts > 60s.

File: cmd/push.go [hunk 2]
```diff
@@ -374,7 +380,7 @@ func (p *PushCmdParams) getSelectedAccounts() ([]string, error) {
 	return []string{}, nil
 }
 
-func multiRequest(nc *nats.Conn, report *store.Report, operation string, subject string, reqData []byte, respHandler func(srv string, data interface{})) int {
+func multiRequest(nc *nats.Conn, report *store.Report, operation string, subject string, reqData []byte, respHandler func(srv string, data interface{}), timeout int) int {
```
Comment (piotrpio) [inline cmd/push.go:383]: I would put `timeout` before `respHandler` to keep handler as the last param.

File: cmd/push.go [hunk 3]
```diff
@@ -57,6 +55,7 @@ push -P -A (all accounts)`,
 	cmd.Flags().StringVarP(&params.removeAcc, "account-removal", "R", "", "remove specific account. Only works with nats-resolver enabled nats-server. Mutually exclusive of prune/diff.")
 	cmd.Flags().StringVarP(&params.sysAcc, "system-account", "", "", "System account for use with nats-resolver enabled nats-server. (Default is system account specified by operator)")
 	cmd.Flags().StringVarP(&params.sysAccUser, "system-user", "", "", "System account user for use with nats-resolver enabled nats-server. (Default to temporarily generated user)")
+	cmd.Flags().IntVarP(&params.timeout, "timeout", "", 1, "timeout in seconds [1-60] to wait for responses from the server (only applicable to nats-resolver configurations, and applies per operation)")
```
Comment (piotrpio) [inline cmd/push.go:58]: Please add note about the default value in description

**Review by piotrpio — CHANGES_REQUESTED** [review]

File: cmd/push.go (hunk 3 above)
Comment (aricart) [reply cmd/push.go:58]:
```bash
$ nsc push -h
Push an account jwt to an Account JWT Server

Usage:
  nsc push (currentAccount)
push -a <accountName>
push -A (all accounts)
push -P
push -P -A (all accounts) [flags]

Examples:
push

Flags:
  -a, --account string                  account name
  -u, --account-jwt-server-url string   set account jwt server url for nsc sync (only http/https/nats urls supported if updating with nsc) If a nats url is provided 
  -R, --account-removal string          remove specific account. Only works with nats-resolver enabled nats-server. Mutually exclusive of prune/diff.
  -A, --all                             push all accounts under the current operator (exclusive of -a)
  -D, --diff                            diff accounts present in nsc env and nats-account-resolver. Mutually exclusive of account-removal/prune.
  -F, --force                           push regardless of validation issues
  -h, --help                            help for push
  -P, --prune                           prune all accounts not under the current operator. Only works with nats-resolver enabled nats-server. Mutually exclusive of account-removal/diff.
      --system-account string           System account for use with nats-resolver enabled nats-server. (Default is system account specified by operator)
      --system-user string              System account user for use with nats-resolver enabled nats-server. (Default to temporarily generated user)
      --timeout int                     timeout in seconds [1-60] to wait for responses from the server (only applicable to nats-resolver configurations, and applies per operation) (default 1)
```

File: cmd/push.go (hunk 1 above)
Comment (aricart) [reply cmd/push.go:301]: I think clamping for this is not a problem - simply doing a check in case they gave a negative value etc.

File: cmd/push.go (hunk 2 above)
Comment (aricart) [reply cmd/push.go]: since that is effectively something related to the connection/etc (we need scatter gather in the go client), I put it after the connection, also refactored some of the param names so that we can understand what is going on in there.

**Review by piotrpio — APPROVED** [review]
LGTM
