### PR TITLE
prevent entity names with path separators

### LINKED ISSUE #398: Role names should be validated
I was looking up what, if any constraints there are with role (operator, account, or user) names and so I tried this.

```
❯ nsc add account foo/bar
[ OK ] generated and stored account key "ACCPV5QZDNXZK3SJSN5RSHO3TVLKPH5GBIXRMAZZU4FJOCYAWDQ3XV3G"
[ OK ] added account "foo/bar"
Error: "foo/bar" not in accounts for operator "stage" in `/Users/ruthb/.nsc/nats`
```

### PR DESCRIPTION
**Pull request by aricart**
[FIX] entity names using a path separator are parsed as a path, which then writes them to the wrong location in the store - this fix generates an error if for such names

FIXES #398

### CODE REVIEW

File: cmd/addaccount.go [hunk 1]
```diff
@@ -180,6 +180,11 @@ func (p *AddAccountParams) Validate(ctx ActionCtx) error {
 		return fmt.Errorf("account name is required")
 	}
 
+	if strings.Contains(p.name, "/") || strings.Contains(p.name, "\\") {
```
Comment (piotrpio) [inline cmd/addaccount.go:183]: You can use `ContainsAny` here (same for other usages in this PR):
```suggestion
	if strings.ContainsAny(p.name, "/\\")

File: cmd/adduser.go [hunk 2]
```diff
@@ -213,6 +213,11 @@ func (p *AddUserParams) Validate(ctx ActionCtx) error {
 		return fmt.Errorf("user name is required")
 	}
 
+	if strings.Contains(p.userName, "/") || strings.Contains(p.userName, "\\") {
```
Comment (piotrpio) [inline cmd/adduser.go:216]:
```suggestion
	if strings.ContainsAny(p.userName, "/\\") {
```

File: cmd/addoperator.go [hunk 3]
```diff
@@ -248,6 +249,10 @@ func (p *AddOperatorParams) Validate(ctx ActionCtx) error {
 		ctx.CurrentCmd().SilenceUsage = false
 		return fmt.Errorf("operator name is required")
 	}
+	if strings.Contains(p.name, "/") || strings.Contains(p.name, "\\") {
```
Comment (piotrpio) [inline cmd/addoperator.go:252]:
```suggestion
	if strings.ContainsAny(p.userName, "/\\") {
```

**Review by piotrpio — APPROVED** [review]
LGTM!
